/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSaudeRouteImport } from './routes/app.saude'
import { Route as AppRecompensasRouteImport } from './routes/app.recompensas'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMentalRouteImport } from './routes/app.mental'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppHidratacaoRouteImport } from './routes/app.hidratacao'
import { Route as AppErgonomiaRouteImport } from './routes/app.ergonomia'
import { Route as AppDesafiosRouteImport } from './routes/app.desafios'
import { Route as AppAvisosRouteImport } from './routes/app.avisos'
import { Route as AdminRecompensasRouteImport } from './routes/admin.recompensas'
import { Route as AdminFuncionariosRouteImport } from './routes/admin.funcionarios'
import { Route as AdminDesafiosRouteImport } from './routes/admin.desafios'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContasRouteImport } from './routes/admin.contas'
import { Route as AdminAvisosRouteImport } from './routes/admin.avisos'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSaudeRoute = AppSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AppRoute,
} as any)
const AppRecompensasRoute = AppRecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMentalRoute = AppMentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHidratacaoRoute = AppHidratacaoRouteImport.update({
  id: '/hidratacao',
  path: '/hidratacao',
  getParentRoute: () => AppRoute,
} as any)
const AppErgonomiaRoute = AppErgonomiaRouteImport.update({
  id: '/ergonomia',
  path: '/ergonomia',
  getParentRoute: () => AppRoute,
} as any)
const AppDesafiosRoute = AppDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AdminRecompensasRoute = AdminRecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuncionariosRoute = AdminFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesafiosRoute = AdminDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContasRoute = AdminContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/desafios': typeof AdminDesafiosRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/recompensas': typeof AdminRecompensasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/ergonomia': typeof AppErgonomiaRoute
  '/app/hidratacao': typeof AppHidratacaoRoute
  '/app/home': typeof AppHomeRoute
  '/app/mental': typeof AppMentalRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/recompensas': typeof AppRecompensasRoute
  '/app/saude': typeof AppSaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/desafios': typeof AdminDesafiosRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/recompensas': typeof AdminRecompensasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/ergonomia': typeof AppErgonomiaRoute
  '/app/hidratacao': typeof AppHidratacaoRoute
  '/app/home': typeof AppHomeRoute
  '/app/mental': typeof AppMentalRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/recompensas': typeof AppRecompensasRoute
  '/app/saude': typeof AppSaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/desafios': typeof AdminDesafiosRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/recompensas': typeof AdminRecompensasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/ergonomia': typeof AppErgonomiaRoute
  '/app/hidratacao': typeof AppHidratacaoRoute
  '/app/home': typeof AppHomeRoute
  '/app/mental': typeof AppMentalRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/recompensas': typeof AppRecompensasRoute
  '/app/saude': typeof AppSaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/admin/alertas'
    | '/admin/avisos'
    | '/admin/contas'
    | '/admin/dashboard'
    | '/admin/desafios'
    | '/admin/funcionarios'
    | '/admin/recompensas'
    | '/app/avisos'
    | '/app/desafios'
    | '/app/ergonomia'
    | '/app/hidratacao'
    | '/app/home'
    | '/app/mental'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/recompensas'
    | '/app/saude'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/admin/alertas'
    | '/admin/avisos'
    | '/admin/contas'
    | '/admin/dashboard'
    | '/admin/desafios'
    | '/admin/funcionarios'
    | '/admin/recompensas'
    | '/app/avisos'
    | '/app/desafios'
    | '/app/ergonomia'
    | '/app/hidratacao'
    | '/app/home'
    | '/app/mental'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/recompensas'
    | '/app/saude'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/admin/alertas'
    | '/admin/avisos'
    | '/admin/contas'
    | '/admin/dashboard'
    | '/admin/desafios'
    | '/admin/funcionarios'
    | '/admin/recompensas'
    | '/app/avisos'
    | '/app/desafios'
    | '/app/ergonomia'
    | '/app/hidratacao'
    | '/app/home'
    | '/app/mental'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/recompensas'
    | '/app/saude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/saude': {
      id: '/app/saude'
      path: '/saude'
      fullPath: '/app/saude'
      preLoaderRoute: typeof AppSaudeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recompensas': {
      id: '/app/recompensas'
      path: '/recompensas'
      fullPath: '/app/recompensas'
      preLoaderRoute: typeof AppRecompensasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mental': {
      id: '/app/mental'
      path: '/mental'
      fullPath: '/app/mental'
      preLoaderRoute: typeof AppMentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hidratacao': {
      id: '/app/hidratacao'
      path: '/hidratacao'
      fullPath: '/app/hidratacao'
      preLoaderRoute: typeof AppHidratacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ergonomia': {
      id: '/app/ergonomia'
      path: '/ergonomia'
      fullPath: '/app/ergonomia'
      preLoaderRoute: typeof AppErgonomiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desafios': {
      id: '/app/desafios'
      path: '/desafios'
      fullPath: '/app/desafios'
      preLoaderRoute: typeof AppDesafiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avisos': {
      id: '/app/avisos'
      path: '/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/recompensas': {
      id: '/admin/recompensas'
      path: '/recompensas'
      fullPath: '/admin/recompensas'
      preLoaderRoute: typeof AdminRecompensasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funcionarios': {
      id: '/admin/funcionarios'
      path: '/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AdminFuncionariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/desafios': {
      id: '/admin/desafios'
      path: '/desafios'
      fullPath: '/admin/desafios'
      preLoaderRoute: typeof AdminDesafiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contas': {
      id: '/admin/contas'
      path: '/contas'
      fullPath: '/admin/contas'
      preLoaderRoute: typeof AdminContasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avisos': {
      id: '/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminAvisosRoute: typeof AdminAvisosRoute
  AdminContasRoute: typeof AdminContasRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDesafiosRoute: typeof AdminDesafiosRoute
  AdminFuncionariosRoute: typeof AdminFuncionariosRoute
  AdminRecompensasRoute: typeof AdminRecompensasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminAvisosRoute: AdminAvisosRoute,
  AdminContasRoute: AdminContasRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDesafiosRoute: AdminDesafiosRoute,
  AdminFuncionariosRoute: AdminFuncionariosRoute,
  AdminRecompensasRoute: AdminRecompensasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAvisosRoute: typeof AppAvisosRoute
  AppDesafiosRoute: typeof AppDesafiosRoute
  AppErgonomiaRoute: typeof AppErgonomiaRoute
  AppHidratacaoRoute: typeof AppHidratacaoRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMentalRoute: typeof AppMentalRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppRecompensasRoute: typeof AppRecompensasRoute
  AppSaudeRoute: typeof AppSaudeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvisosRoute: AppAvisosRoute,
  AppDesafiosRoute: AppDesafiosRoute,
  AppErgonomiaRoute: AppErgonomiaRoute,
  AppHidratacaoRoute: AppHidratacaoRoute,
  AppHomeRoute: AppHomeRoute,
  AppMentalRoute: AppMentalRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppRecompensasRoute: AppRecompensasRoute,
  AppSaudeRoute: AppSaudeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
